server:
  port: 19101
spring:
  application:
    name: course-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?characterEncoding=utf-8&serverTimezone=UTC
    password:
    username: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18081/eureka
pagehelper:
  helper-dialect: mysql
mybatis:
  mapper-locations: classpath:mapping/*.xml