
server:
  port: 11111
solr:
  baseUrl: http://localhost:8080/solr
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hzw?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qf.j1902.pojo