
server:
  port: 18201
spring:
  application:
    name: all-portal
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18081/eureka